import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/navigation/sidebar/sidebar";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "./_providers/auth-provider";
import { CXThemeProvider } from "./_providers/theme-provider";
import { NavigationGuardProvider } from "./_providers/navigation-guard-provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Customer Experience",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full min-w-full flex">
        <CXThemeProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <NavigationGuardProvider>
            <AuthProvider>
              <SideBar />
              {children}
            </AuthProvider>
          </NavigationGuardProvider>
        </CXThemeProvider>
        </body>
    </html>
  );
}
